feat/DEST-357/Adding circle ci integration
hevoio/trino-hive pull request #5
Opened 2024-07-15 16:27 UTC by DhruvilSureshPatel

2024-07-18 04:54 UTC, 91pratyush requested changes

2024-07-18 04:54 UTC, 91pratyush commented on .circleci/config.yml
> +            ansible-playbook -i environments/<< pipeline.parameters.environment>> trino.yml
Rename playbook to `trino-service` to keep it consistent with all names.

2024-07-18 04:58 UTC, 91pratyush commented
@DhruvilSureshPatel add CodeOwners for this repo.

2024-07-18 15:53 UTC, hkarira1 commented on .circleci/config.yml
> +            ansible-playbook -i environments/<< pipeline.parameters.environment>> trino.yml
changed the playbook name @91pratyush

2024-07-19 09:24 UTC, vighneshhevo commented on .circleci/config.yml
> +            jinja -E ENVIRONMENT -E ECS_TASK_ROLE_ARN -E ECS_EXECUTION_ROLE_ARN -E CONTAINER_IMAGE -E MODULE -E AWS_REGION -E CIRCLE_SHA1 -E CORALOGIX_API_KEY -E FIRELENS_FLUENTBIT_CONFIG_BUCKET .dep
what will CIRCLE_SHA1 hold?

2024-07-19 09:24 UTC, vighneshhevo commented on .circleci/config.yml
> +    default: "master"
can we change the default branch to dev as we have given default environment to test?

2024-07-19 09:24 UTC, vighneshhevo commented on .circleci/config.yml
> +            export MODULE="trino-service"
Nit: can we replace `module` with `application`?

2024-07-22 06:58 UTC, tremendoustj approved these changes

2024-07-22 14:10 UTC, hkarira1 commented on .circleci/config.yml
> +            jinja -E ENVIRONMENT -E ECS_TASK_ROLE_ARN -E ECS_EXECUTION_ROLE_ARN -E CONTAINER_IMAGE -E MODULE -E AWS_REGION -E CIRCLE_SHA1 -E CORALOGIX_API_KEY -E FIRELENS_FLUENTBIT_CONFIG_BUCKET .dep
I have removed this as this is not required.

2024-07-22 14:11 UTC, 91pratyush approved these changes

2024-07-22 14:11 UTC, hkarira1 commented on .circleci/config.yml
> +    default: "master"
changed this to dev everywhere.

2024-07-22 14:47 UTC, 91pratyush approved these changes

2024-07-22 15:14 UTC, tremendoustj approved these changes

2024-07-22 15:25 UTC, merged